name: Build .NET Core WebApp

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    
    # dotnet build and publish
    - name: Build with dotnet
      run: dotnet build "src" --configuration Release
    - name: dotnet publish
      run: dotnet publish "src" -c Release -o dotnetcorewebapp
      
